series = [
    {
        "season": "IMSA iRacing Series - 2026 Season 1",
        "track": "Watkins Glen International - Boot",
        "car_class": "GTP",
        "cars": ["Acura ARX-06 GTP",
            "BMW M Hybrid V8",
            "Cadillac V-Series.R GTP",
            "Ferrari 499P",
            "Porsche 963 GTP"],
        "category": "sports_car",
        "license": "A",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 29,
        "average_lap": 0.001089895,
        "corners_per_lap": 12,
        "expected_time": 0.031606946,
        "corners": 348
    },
    {
        "season": "IMSA iRacing Series - 2026 Season 1",
        "track": "Watkins Glen International - Boot",
        "car_class": "Dallara P217",
        "category": "sports_car",
        "license": "A",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 28,
        "average_lap": 0.001146659,
        "corners_per_lap": 12,
        "expected_time": 0.03210644,
        "corners": 336
    },
    {
        "season": "IMSA iRacing Series - 2026 Season 1",
        "track": "Watkins Glen International - Boot",
        "car_class": "IMSA23",
        "category": "sports_car",
        "license": "A",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 26,
        "average_lap": 0.001229744,
        "corners_per_lap": 12,
        "expected_time": 0.03197335,
        "corners": 312
    },
    {
        "season": "IMSA iRacing Series - Fixed - 2026 Season 1",
        "track": "Watkins Glen International - Boot",
        "car_class": "GTP",
        "category": "sports_car",
        "license": "A",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 23,
        "average_lap": 0.001091407,
        "corners_per_lap": 12,
        "expected_time": 0.02510237,
        "corners": 276
    },
    {
        "season": "IMSA iRacing Series - Fixed - 2026 Season 1",
        "track": "Watkins Glen International - Boot",
        "car_class": "Dallara P217",
        "category": "sports_car",
        "license": "A",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 22,
        "average_lap": 0.001155741,
        "corners_per_lap": 12,
        "expected_time": 0.025426296,
        "corners": 264
    },
    {
        "season": "IMSA iRacing Series - Fixed - 2026 Season 1",
        "track": "Watkins Glen International - Boot",
        "car_class": "IMSA23",
        "category": "sports_car",
        "license": "A",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 21,
        "average_lap": 0.001230591,
        "corners_per_lap": 12,
        "expected_time": 0.02584242,
        "corners": 252
    },
    {
        "season": "Formula A - Cosworth Cup Grand Prix - Fixed - 2026 Season 1",
        "track": "Red Bull Ring - Grand Prix",
        "car_class": "Mercedes-AMG W13 E Performance",
        "category": "formula_car",
        "license": "A",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 18,
        "average_lap": 0.000815769,
        "corners_per_lap": 9,
        "expected_time": 0.014683833,
        "corners": 162
    },
    {
        "season": "GTE Sprint Series - 2026 Season 1",
        "track": "Autódromo Hermanos Rodríguez - Grand Prix",
        "car_class": "GTE Class",
        "category": "sports_car",
        "license": "B",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 27,
        "average_lap": 0.001165813,
        "corners_per_lap": 17,
        "expected_time": 0.031476938,
        "corners": 459
    },
    {
        "season": "INDYCAR Series - 2026 Season 1",
        "track": "Watkins Glen International - Boot",
        "car_class": "Dallara IR18",
        "category": "formula_car",
        "license": "B",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 37,
        "average_lap": 0.00103853,
        "corners_per_lap": 12,
        "expected_time": 0.038425613,
        "corners": 444
    },
    {
        "season": "GT Sprint Series by Simucube - 2026 Season 1",
        "track": "Shell V-Power Motorsport Park at The Bend - International Circuit",
        "car_class": "GT3 2025",
        "category": "sports_car",
        "license": "B",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 22,
        "average_lap": 0.001277159,
        "corners_per_lap": 18,
        "expected_time": 0.028097488,
        "corners": 396
    },
    {
        "season": "Formula B - Super Formula Series 2026 Season 1",
        "track": "Road Atlanta - Full Course",
        "car_class": "Super Formula SF23",
        "category": "formula_car",
        "license": "B",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 33,
        "average_lap": 0.000746258,
        "corners_per_lap": 12,
        "expected_time": 0.024626517,
        "corners": 396
    },
    {
        "season": "iRacing GT3 Regional Tour - Americas - 2026 Season 1",
        "track": "Barber Motorsports Park - Full Course",
        "car_class": "GT3 2025",
        "category": "sports_car",
        "license": "B",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 15,
        "average_lap": 0.000947362,
        "corners_per_lap": 16,
        "expected_time": 0.014210434,
        "corners": 240
    },
    {
        "season": "iRacing GT3 Regional Tour - Asia Pacific - 2026 Season 1",
        "track": "Sandown International Motor Raceway",
        "car_class": "GT3 2025",
        "category": "sports_car",
        "license": "B",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 18,
        "average_lap": 0.000781449,
        "corners_per_lap": 13,
        "expected_time": 0.014066083,
        "corners": 234
    },
    {
        "season": "Formula B - Super Formula Series - Fixed - 2026 Season 1",
        "track": "Road Atlanta - Full Course",
        "car_class": "Super Formula SF23",
        "category": "formula_car",
        "license": "B",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 19,
        "average_lap": 0.000739405,
        "corners_per_lap": 12,
        "expected_time": 0.014048697,
        "corners": 228
    },
    {
        "season": "GT3 Challenge Fixed by Fanatec - 2026 Season 1",
        "track": "Shell V-Power Motorsport Park at The Bend - International Circuit",
        "car_class": "GT3 2025",
        "category": "sports_car",
        "license": "B",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 12,
        "average_lap": 0.001240039,
        "corners_per_lap": 18,
        "expected_time": 0.014880472,
        "corners": 216
    },
    {
        "season": "iRacing GT3 Regional Tour - Europe - 2026 Season 1",
        "track": "MotorLand Aragón - Grand Prix",
        "car_class": "GT3 2025",
        "category": "sports_car",
        "license": "B",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 11,
        "average_lap": 0.001341632,
        "corners_per_lap": 18,
        "expected_time": 0.014757951,
        "corners": 198
    },
    {
        "season": "Prototype Challenge  - 2026 Season 1 - Fixed",
        "track": "Watkins Glen International - Boot",
        "car_class": "GTP",
        "category": "sports_car",
        "license": "B",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 13,
        "average_lap": 0.001076355,
        "corners_per_lap": 12,
        "expected_time": 0.013992619,
        "corners": 156
    },
    {
        "season": "LMP2 Challenge  - 2026 Season 1 - Fixed",
        "track": "Watkins Glen International - Boot",
        "car_class": "Dallara P217",
        "category": "sports_car",
        "license": "B",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 13,
        "average_lap": 0.00112378,
        "corners_per_lap": 12,
        "expected_time": 0.014609141,
        "corners": 156
    },
    {
        "season": "INDYCAR Series - Fixed - 2026 Season 1",
        "track": "Watkins Glen International - Boot",
        "car_class": "Dallara IR18",
        "category": "formula_car",
        "license": "B",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 10,
        "average_lap": 0.001039421,
        "corners_per_lap": 12,
        "expected_time": 0.010394213,
        "corners": 120
    },
    {
        "season": "Ring Meister - 2026 Season 1",
        "track": "Nürburgring Nordschleife - Industriefahrten",
        "car_class": "Cadillac CTS-VR",
        "category": "sports_car",
        "license": "C",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 3,
        "average_lap": 0.004666597,
        "corners_per_lap": 154,
        "expected_time": 0.013999792,
        "corners": 462
    },
    {
        "season": "Dallara Formula iR - 2026 Season 1",
        "track": "Charlotte Motor Speedway  - Oval",
        "car_class": "Dallara iR-01",
        "category": "oval",
        "license": "C",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 80,
        "average_lap": 0.000265985,
        "corners_per_lap": 4,
        "expected_time": 0.021278796,
        "corners": 320
    },
    {
        "season": "Sports Car Challenge by Falken Tyre - 2026 Season 1",
        "track": "Miami International Autodrome - Grand Prix",
        "car_class": "Ligier JS P320",
        "category": "sports_car",
        "license": "C",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 16,
        "average_lap": 0.001308542,
        "corners_per_lap": 17,
        "expected_time": 0.020936667,
        "corners": 272
    },
    {
        "season": "Sports Car Challenge by Falken Tyre - 2026 Season 1",
        "track": "Miami International Autodrome - Grand Prix",
        "car_class": "GT4 Class",
        "category": "sports_car",
        "license": "C",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 15,
        "average_lap": 0.001471954,
        "corners_per_lap": 17,
        "expected_time": 0.022079306,
        "corners": 255
    },
    {
        "season": "Radical Esports Cup - 2026 Season 1",
        "track": "Rudskogen Motorsenter",
        "car_class": "Radical SR10",
        "category": "sports_car",
        "license": "C",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 18,
        "average_lap": 0.000908116,
        "corners_per_lap": 14,
        "expected_time": 0.016346083,
        "corners": 252
    },
    {
        "season": "Supercars Series - Australian Servers - 2026 Season 1",
        "track": "[Legacy] Silverstone Circuit - 2008 - Historical Grand Prix",
        "car_class": "Supercars Gen 3",
        "category": "sports_car",
        "license": "C",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 23,
        "average_lap": 0.001245869,
        "corners_per_lap": 10,
        "expected_time": 0.028654992,
        "corners": 230
    },
    {
        "season": "Indy NXT Road Series - Fixed - 2026 Season 1",
        "track": "Autódromo José Carlos Pace - Grand Prix",
        "car_class": "Dallara IL15",
        "category": "formula_car",
        "license": "C",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 15,
        "average_lap": 0.000974478,
        "corners_per_lap": 15,
        "expected_time": 0.01461717,
        "corners": 225
    },
    {
        "season": "Formula C -  Dallara F3 Series - 2026 Season 1",
        "track": "Circuit de Barcelona Catalunya - Historic",
        "car_class": "Dallara F3",
        "category": "formula_car",
        "license": "C",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 17,
        "average_lap": 0.001084244,
        "corners_per_lap": 13,
        "expected_time": 0.018432152,
        "corners": 221
    },
    {
        "season": "Advanced Mazda MX-5 Cup by Heusinkveld - 2026 Season 1",
        "track": "Miami International Autodrome - Grand Prix",
        "car_class": "Mazda MX-5 Cup 2016",
        "category": "sports_car",
        "license": "C",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 13,
        "average_lap": 0.001616736,
        "corners_per_lap": 17,
        "expected_time": 0.021017569,
        "corners": 221
    },
    {
        "season": "Formula C - Dallara F3 Series -2026 Season 1 - Fixed",
        "track": "Circuit de Barcelona Catalunya - Historic",
        "car_class": "Dallara F3",
        "category": "formula_car",
        "license": "C",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 16,
        "average_lap": 0.001093037,
        "corners_per_lap": 13,
        "expected_time": 0.017488593,
        "corners": 208
    },
    {
        "season": "Formula C - Super Formula Lights by RSS - 2026 Season 1",
        "track": "Autodromo Nazionale Monza - Grand Prix",
        "car_class": "Super Formula Lights",
        "category": "formula_car",
        "license": "C",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 18,
        "average_lap": 0.001175547,
        "corners_per_lap": 11,
        "expected_time": 0.021159854,
        "corners": 198
    },
    {
        "season": "LMP3 Trophy - 2026 Season 1",
        "track": "Miami International Autodrome - Grand Prix",
        "car_class": "Ligier JS P320",
        "category": "sports_car",
        "license": "C",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 11,
        "average_lap": 0.001301757,
        "corners_per_lap": 17,
        "expected_time": 0.014319326,
        "corners": 187
    },
    {
        "season": "iRacing Porsche Cup - Fixed by CONSPIT - 2026 Season 1",
        "track": "Autodromo Nazionale Monza - Grand Prix",
        "car_class": "Porsche 911 Cup (992.2)",
        "category": "sports_car",
        "license": "C",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 14,
        "average_lap": 0.00123813,
        "corners_per_lap": 11,
        "expected_time": 0.017333815,
        "corners": 154
    },
    {
        "season": "iRacing Porsche Cup by CONSPIT - 2026 Season 1",
        "track": "Autodromo Nazionale Monza - Grand Prix",
        "car_class": "Porsche 911 Cup (992.2)",
        "category": "sports_car",
        "license": "C",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 14,
        "average_lap": 0.001239493,
        "corners_per_lap": 11,
        "expected_time": 0.017352903,
        "corners": 154
    },
    {
        "season": "Ferrari 296 Challenge 2026 Season 1",
        "track": "Circuit de Spa-Francorchamps - Grand Prix Pits",
        "car_class": "Ferrari 296 Challenge",
        "category": "sports_car",
        "license": "C",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 7,
        "average_lap": 0.001574042,
        "corners_per_lap": 21,
        "expected_time": 0.011018292,
        "corners": 147
    },
    {
        "season": "Formula C - Super Formula Lights - Fixed by RSS - 2026 Season 1",
        "track": "Autodromo Nazionale Monza - Grand Prix",
        "car_class": "Super Formula Lights",
        "category": "formula_car",
        "license": "C",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 12,
        "average_lap": 0.001188837,
        "corners_per_lap": 11,
        "expected_time": 0.014266042,
        "corners": 132
    },
    {
        "season": "Mission R Challenge - 2026 Season 1",
        "track": "Nürburgring Nordschleife - Industriefahrten",
        "car_class": "Porsche Mission R",
        "category": "sports_car",
        "license": "D",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 3,
        "average_lap": 0.004697455,
        "corners_per_lap": 154,
        "expected_time": 0.014092365,
        "corners": 462
    },
    {
        "season": "Legends Road Cup by Go Motorsports Shop - 2026 Season 1",
        "track": "Auto Club Speedway - Interior",
        "car_class": "Legends",
        "category": "sports_car",
        "license": "D",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 13,
        "average_lap": 0.000835432,
        "corners_per_lap": 17,
        "expected_time": 0.010860612,
        "corners": 221
    },
    {
        "season": "Clio Cup - 2026 Season 1",
        "track": "Virginia International Raceway - North Course",
        "car_class": "Renault Clio",
        "category": "sports_car",
        "license": "D",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 10,
        "average_lap": 0.001107995,
        "corners_per_lap": 20,
        "expected_time": 0.011079954,
        "corners": 200
    },
    {
        "season": "Production Car Challenge by Sim-Lab - 2026 Season 1",
        "track": "Sonoma Raceway - Sportscar Alt",
        "car_class": "Renault Clio",
        "category": "sports_car",
        "license": "D",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 15,
        "average_lap": 0.001291597,
        "corners_per_lap": 12,
        "expected_time": 0.019373958,
        "corners": 180
    },
    {
        "season": "Production Car Challenge by Sim-Lab - 2026 Season 1",
        "track": "Sonoma Raceway - Sportscar Alt",
        "car_class": "Toyota GR86",
        "category": "sports_car",
        "license": "D",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 15,
        "average_lap": 0.001228639,
        "corners_per_lap": 12,
        "expected_time": 0.018429583,
        "corners": 180
    },
    {
        "season": "Production Car Challenge by Sim-Lab - 2026 Season 1",
        "track": "Sonoma Raceway - Sportscar Alt",
        "car_class": "BMW M2 CS Racing",
        "category": "sports_car",
        "license": "D",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 15,
        "average_lap": 0.001208065,
        "corners_per_lap": 12,
        "expected_time": 0.018120972,
        "corners": 180
    },
    {
        "season": "Production Car Challenge by Sim-Lab - 2026 Season 1",
        "track": "Sonoma Raceway - Sportscar Alt",
        "car_class": "Mazda MX-5 Cup 2016",
        "category": "sports_car",
        "license": "D",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 15,
        "average_lap": 0.001270934,
        "corners_per_lap": 12,
        "expected_time": 0.01906401,
        "corners": 180
    },
    {
        "season": "Spec Racer Ford Challenge - 2026 Season 1",
        "track": "Motorsport Arena Oschersleben - B Course",
        "car_class": "Spec Racer Ford",
        "category": "sports_car",
        "license": "D",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 22,
        "average_lap": 0.000785541,
        "corners_per_lap": 8,
        "expected_time": 0.017281891,
        "corners": 176
    },
    {
        "season": "GT4 Falken Tyre Challenge - 2026 Season 1",
        "track": "Miami International Autodrome - Grand Prix",
        "car_class": "GT4 Class",
        "category": "sports_car",
        "license": "D",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 10,
        "average_lap": 0.001455331,
        "corners_per_lap": 17,
        "expected_time": 0.01455331,
        "corners": 170
    },
    {
        "season": "FIA Formula 4 Challenge - Fixed - 2026 Season 1",
        "track": "Oulton Park Circuit - International",
        "car_class": "FIA F4",
        "category": "formula_car",
        "license": "D",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 10,
        "average_lap": 0.001090336,
        "corners_per_lap": 17,
        "expected_time": 0.010903356,
        "corners": 170
    },
    {
        "season": "Global Sports Car Challenge by Fanatec - 2026 Season 1",
        "track": "Road America - Full Course",
        "car_class": "Kia Optima",
        "category": "sports_car",
        "license": "D",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 12,
        "average_lap": 0,
        "corners_per_lap": 14,
        "expected_time": 0,
        "corners": 168
    },
    {
        "season": "Global Sports Car Challenge by Fanatec - 2026 Season 1",
        "track": "Road America - Full Course",
        "car_class": "Cadillac CTS-VR",
        "category": "sports_car",
        "license": "D",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 12,
        "average_lap": 0.001515118,
        "corners_per_lap": 14,
        "expected_time": 0.018181417,
        "corners": 168
    },
    {
        "season": "FIA F4 Esports Regional Tour - Europe - 2026 Season 1",
        "track": "Rudskogen Motorsenter",
        "car_class": "FIA F4",
        "category": "formula_car",
        "license": "D",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 12,
        "average_lap": 0.000927906,
        "corners_per_lap": 14,
        "expected_time": 0.011134875,
        "corners": 168
    },
    {
        "season": "Skip Barber Race Series - 2026 Season 1",
        "track": "Phillip Island Circuit",
        "car_class": "Skip Barber Race Series",
        "category": "formula_car",
        "license": "D",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 14,
        "average_lap": 0.001262064,
        "corners_per_lap": 12,
        "expected_time": 0.017668891,
        "corners": 168
    },
    {
        "season": "FIA F4 Esports Regional Tour - America - 2026 Season 1",
        "track": "Lime Rock Park - Grand Prix",
        "car_class": "FIA F4",
        "category": "formula_car",
        "license": "D",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 18,
        "average_lap": 0.00059319,
        "corners_per_lap": 9,
        "expected_time": 0.010677417,
        "corners": 162
    },
    {
        "season": "TCR Virtual Challenge - 2026 Season 1",
        "track": "Summit Point Raceway - Summit Point Raceway",
        "car_class": "Touring Car",
        "category": "sports_car",
        "license": "D",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 16,
        "average_lap": 0.000879933,
        "corners_per_lap": 10,
        "expected_time": 0.014078926,
        "corners": 160
    },
    {
        "season": "TCR Virtual Challenge - Fixed - 2026 Season 1",
        "track": "Summit Point Raceway - Summit Point Raceway",
        "car_class": "Touring Car",
        "category": "sports_car",
        "license": "D",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 16,
        "average_lap": 0.000878363,
        "corners_per_lap": 10,
        "expected_time": 0.014053815,
        "corners": 160
    },
    {
        "season": "FIA F4 Esports Regional Tour - Asia Pacific - 2026 Season 1",
        "track": "Winton Motor Raceway - National Circuit",
        "car_class": "FIA F4",
        "category": "formula_car",
        "license": "D",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 12,
        "average_lap": 0.000917201,
        "corners_per_lap": 12,
        "expected_time": 0.011006417,
        "corners": 144
    },
    {
        "season": "Motorsport UK FF 1600 Trophy by Thrustmaster - 2026 Season 1",
        "track": "Phillip Island Circuit",
        "car_class": "Ray FF1600",
        "category": "formula_car",
        "license": "D",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 12,
        "average_lap": 0.001173601,
        "corners_per_lap": 12,
        "expected_time": 0.014083208,
        "corners": 144
    },
    {
        "season": "BMW M Power Challenge - 2026 Season 1",
        "track": "Circuit de Spa-Francorchamps - Grand Prix Pits",
        "car_class": "BMW M2 CS Racing",
        "category": "sports_car",
        "license": "D",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 6,
        "average_lap": 0.001815933,
        "corners_per_lap": 21,
        "expected_time": 0.010895597,
        "corners": 126
    },
    {
        "season": "Rain Master - 2026 Season 1",
        "track": "Circuit de Spa-Francorchamps - Grand Prix Pits",
        "car_class": "GT3 Class",
        "category": "sports_car",
        "license": "D",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 6,
        "average_lap": 0.001821249,
        "corners_per_lap": 21,
        "expected_time": 0.010927493,
        "corners": 126
    },
    {
        "season": "US Open Wheel D - USF 2000 Series  - 2026 Season 1 - Fixed",
        "track": "Autódromo Hermanos Rodríguez - Oval",
        "car_class": "USF 2000",
        "category": "oval",
        "license": "D",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 30,
        "average_lap": 0.000353922,
        "corners_per_lap": 4,
        "expected_time": 0.010617674,
        "corners": 120
    },
    {
        "season": "Mustang Skip Barber Challenge - 2026 Season 1",
        "track": "Sonoma Raceway - Sportscar Alt",
        "car_class": "Ford Mustang GT4",
        "category": "sports_car",
        "license": "D",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 10,
        "average_lap": 0.001144515,
        "corners_per_lap": 12,
        "expected_time": 0.01144515,
        "corners": 120
    },
    {
        "season": "Toyota GR86 Cup by SIMAGIC - 2026 Season 1",
        "track": "Summit Point Raceway - Summit Point Raceway",
        "car_class": "Toyota GR86",
        "category": "sports_car",
        "license": "D",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 12,
        "average_lap": 0.000916418,
        "corners_per_lap": 10,
        "expected_time": 0.010997014,
        "corners": 120
    },
    {
        "season": "BMW M2 Cup by Nitro Concepts - 2026 Season 1",
        "track": "Circuit de Lédenon",
        "car_class": "BMW M2 CS Racing",
        "category": "sports_car",
        "license": "R",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 8,
        "average_lap": 0.00104476,
        "corners_per_lap": 13,
        "expected_time": 0.008358083,
        "corners": 104
    },
    {
        "season": "Global Mazda MX-5 Cup by Fanatec - 2026 Season 1",
        "track": "Circuit de Lédenon",
        "car_class": "Mazda MX-5 Cup 2016",
        "category": "sports_car",
        "license": "R",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 8,
        "average_lap": 0.001086572,
        "corners_per_lap": 13,
        "expected_time": 0.008692574,
        "corners": 104
    },
    {
        "season": "Formula 1600 Rookie Series - 2026 Season 1",
        "track": "Summit Point Raceway - Summit Point Raceway",
        "car_class": "Ray FF1600",
        "category": "formula_car",
        "license": "R",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 10,
        "average_lap": 0.000881949,
        "corners_per_lap": 10,
        "expected_time": 0.008819491,
        "corners": 100
    },
    {
        "season": "Formula Vee Series by trophi.ai - 2026 Season 1",
        "track": "Summit Point Raceway - Summit Point Raceway",
        "car_class": "Formula Vee",
        "category": "formula_car",
        "license": "R",
        "week_start": "2026-01-27",
        "week": 7,
        "laps": 9,
        "average_lap": 0.001017323,
        "corners_per_lap": 10,
        "expected_time": 0.009155906,
        "corners": 90
    }
]